name: publish npm

on:
  push:
    tags:
    - v*.*.*
  workflow_dispatch:


permissions:
  contents: write

jobs:
  call-workflow-passing-data:
    uses: dappsteros-io/github/.github/workflows/npm_release.yml@main
    secrets:
      NPM_TOKEN_PRIVATE: ${{ secrets.NPM_TOKEN }}
