name: goreleaser

on:
  push:
    tags:
    - v*.*.*
permissions:
  contents: write
jobs:
  call-workflow-passing-data:
    uses: dappsteros-io/github/.github/workflows/go_release.yml@main
    with:
      project-name: DappsterOS-MessageBus
      file-name: dappsteros-message-bus
    secrets:
      OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
